# Generated by Django 4.2.11 on 2026-07-17 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', models.JSONField()),
                ('metadata', models.JSONField(default=dict)),
                ('embedding_model', models.CharField(max_length=100)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rag_embedding', to='products.product')),
            ],
            options={
                'ordering': ['product_id'],
            },
        ),
    ]
